name: DeepSpeed Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the docker image to use for build'
        required: true
        default: 'paladinium/alltalk_deepspeed:latest'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          docker-images: false
          swap-storage: true
      - name: Test that setup-nvidia works
        uses: ./.github/actions/setup-nvidia
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ github.event.inputs.tag }}
          options: -v ${{ github.workspace }}/build:/deepspeed --gpus=all
          run: |
            /build_deepspeed.sh
      - name: Upload whl as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'deepspeed-whl'
          path: ${{ github.workspace }}/build/*.whl