name: DeepSpeed Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the docker image to use for build'
        required: true
        default: 'paladinium/alltalk_deepspeed:latest'

permissions:
  contents: read

jobs:
  build:
    runs-on: another-ubuntu-4cores-with-gpu

    steps:
      - name: nvidia-smi
        run: nvidia-smi
      - name: lsb_release
        run: lsb_release -a
      - name: Update to CUDA 12.6
        run: |
          wget --no-verbose --progress=bar:force:noscroll https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget --no-verbose --progress=bar:force:noscroll https://developer.download.nvidia.com/compute/cuda/12.6.0/local_installers/cuda-repo-ubuntu2204-12-6-local_12.6.0-560.28.03-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2204-12-6-local_12.6.0-560.28.03-1_amd64.deb
          sudo ls -ltr /usr/share/keyrings/
          sudo ls -l /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg
          sudo cp /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo ls -ltr /usr/share/keyrings/
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-6
      - name: nvidia-smi
        run: nvidia-smi
      - name: Run the build process with Docker
        uses: addnab/docker-run-action@v3
        with:
          image: ${{ github.event.inputs.tag }}
          options: -v ${{ github.workspace }}/build:/deepspeed --gpus=all
          run: |
            /build_deepspeed.sh
      - name: Upload whl as artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'deepspeed-whl'
          path: ${{ github.workspace }}/build/*.whl