name: DeepSpeed Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag of the docker image to use for build'
        required: true
        default: 'paladinium/alltalk_deepspeed:latest'

permissions:
  contents: read

jobs:
  build:
    runs-on: another-ubuntu-4cores-with-gpu

    steps:
      - name: nvidia-smi
        run: nvidia-smi
      - name: lsb_release
        run: lsb_release -a
      - name: Update to CUDA 12.6
        run: |
          wget --no-verbose --progress=bar:force:noscroll https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/x86_64/cuda-ubuntu2204.pin
          sudo mv cuda-ubuntu2204.pin /etc/apt/preferences.d/cuda-repository-pin-600
          wget --no-verbose --progress=bar:force:noscroll https://developer.download.nvidia.com/compute/cuda/12.6.0/local_installers/cuda-repo-ubuntu2204-12-6-local_12.6.0-560.28.03-1_amd64.deb
          sudo dpkg -i cuda-repo-ubuntu2204-12-6-local_12.6.0-560.28.03-1_amd64.deb
          sudo ls -ltr /usr/share/keyrings/
          sudo ls -l /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg
          sudo cp /var/cuda-repo-ubuntu2204-12-6-local/cuda-*-keyring.gpg /usr/share/keyrings/
          sudo chmod uog+r /usr/share/keyrings/cuda-*-keyring.gpg
          sudo ls -ltr /usr/share/keyrings/
          sudo apt-get update
          sudo apt-get -y install cuda-toolkit-12-6
      - name: nvidia-smi
        run: nvidia-smi
      - name: update-cuda
        run: |
          sudo update-alternatives --set cufile.json /usr/local/cuda-12.6/gds/cufile.json
          sudo update-alternatives --set cuda /usr/local/cuda-12.6
          sudo update-alternatives --set cuda-12 /usr/local/cuda-12.6
      - name: nvidia-smi
        run: nvidia-smi
#      - name: Run the build process with Docker
#        uses: addnab/docker-run-action@v3
#        with:
#          image: ${{ github.event.inputs.tag }}
#          options: -v ${{ github.workspace }}/build:/deepspeed --gpus=all
#          run: |
#            /build_deepspeed.sh
#      - name: Upload whl as artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: 'deepspeed-whl'
#          path: ${{ github.workspace }}/build/*.whl
#      - update-alternatives: using /usr/local/cuda-12.6/gds/cufile.json to provide /etc/cufile.json (cufile.json) in auto mode
#      - update-alternatives: using /usr/local/cuda-12.6 to provide /usr/local/cuda (cuda) in auto mode
#      - update-alternatives: using /usr/local/cuda-12.6 to provide /usr/local/cuda-12 (cuda-12) in auto mode
#      - update-alternatives: using /opt/nvidia/nsight-systems/2024.5.1/target-linux-x64/nsys to provide /usr/local/bin/nsys (nsys) in auto mode
#      - update-alternatives: using /opt/nvidia/nsight-systems/2024.5.1/host-linux-x64/nsys-ui to provide /usr/local/bin/nsys-ui (nsys-ui) in auto mode
#      -->  https://stackoverflow.com/questions/45477133/how-to-change-cuda-version
#
#      - name: update-nvidia-drivers
#        run: sudo ubuntu-drivers install