name: Publish Docker v2

on:
  workflow_dispatch:

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read variables
        run: |
          source ./docker/variables.sh
          for key in "${!ALLTALK_VARS[@]}"
          do
            echo "${key}=${ALLTALK_VARS[${key}]}"
            echo "${key}=${ALLTALK_VARS[${key}]}" >> $GITHUB_ENV
          done

      - name: Check variables
        run: echo "CUDA VERSION=${{ env.CUDA_VERSION }}"